modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL="https://github.com/CottonMC/LibGUI/issues"

[[mods]]
modId = "libgui_common"
version = "${version}"
displayName = "LibGui"
displayURL = "https://github.com/CottonMC/LibGUI/"

authors = "Falkreon, Juuz"
description = "Easy grid-based GUIs for Fabric"
logoFile = "assets/libgui/icon.png"

displayTest = "IGNORE_ALL_VERSION"

[[dependencies.libgui_common]]
modId = "minecraft"
mandatory = true
versionRange = "[26.1, 26.2)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "mixins.libgui.json"

